### ISSUE TITLE
JavaScript Ninja

### ISSUE THREAD

**Issue by RobsonVinicius** [RobsonVinicius/JavaScriptNinja#1]
### Aula 01

- [x] Introdução 
- [x] Variáveis e tipos de dados
- [x] Operadores aritméticos
- [x] Operadores de igualdade e relacionais
- [x] Funções
- [x] Desafio da semana

### Aula 02

- [x] Revisão Desafio da semana 01
- [x] Operadores Lógicos
- [x] Operadores Unários
- [x] Instruções condicionais - IF
- [x] Desafio da semana #02

### Aula 03

- [x] Revisão do desafio da semana 02 - Parte 1
- [x] Revisão do desafio da semana 02 - Parte 2
- [x] Revisão do desafio da semana 02 - Parte 3
- [x] Tipos de dados e objetos
- [x] Métodos de objeto
- [ ] Métodos de objeto (continuação) e desafio da semana #03

### Aula 04

- [ ] Revisão do desafio da semana 03 - Parte 1
- [ ] Revisão do desafio da semana 03 - Parte 2
- [ ] Truthy e Falsy
- [ ] Condicional Ternário 
- [ ] Condicional Ternário 
- [ ] Escopo de variáveis e funções
- [ ] Desafio da semana #04

### Aula 05

- [ ] Revisão do desafio da semana #04 - Parte 1
- [ ] Revisão do desafio da semana #04 - Parte 2
- [ ] Revisão do desafio da semana #04 - Parte 3
- [ ] Retorno de funções com arrays e objetos
- [ ] Parâmetros de Funções como arrays e objetos
- [ ] Desafio da semana #05

### Aula 06

- [ ] Revisão Desafio da semana #05 - Parte 1
- [ ] Revisão Desafio da semana #05 - Parte 2
- [ ] Revisão Desafio da semana #05 - Parte 3
- [ ] Revisão Desafio da semana #05 - Parte 4
- [ ] Operador virgula e estrutura condicional switch
- [ ] Estrutura de repetição While e desafio da semana #06

### Aula 07

- [ ] Revisão do desafio da semana #06 - Parte 1
- [ ] Revisão do desafio da semana #06 - Parte 2
- [ ] O operador módulo 
- [ ] Arrays - a propriedade length
- [ ] Arrays - método "push()" e Loop "for"
- [ ] Desafio da semana #07

### Aula 08

- [ ] Revisão Desafio semana #07
- [ ]  A importância de nomear funções
- [ ] Introdução à Functional Programming
- [ ] Functional Programming - Parte 2
- [ ] Functional Programming - Parte 3
- [ ] Desafio da semana #08

### Aula 09

- [ ] Revisão desafio semana #08 - Parte 1
- [ ] Revisão desafio semana #08 - Parte 2
- [ ] Escopo de funções
- [ ] hoisting
- [ ] IIFE - Immediately Invoked Function Expression
- [ ] Desafio semana #09

### Aula 10

- [ ] Revisão desafio da semana #09 - Parte 1
- [ ] Revisão desafio da semana #09 - Parte 2
- [ ] Revisão desafio da semana #09 - Parte 3
- [ ] Wrapper Objetcs
- [ ] typeof
- [ ] Desafio da semana #10

### Aula 11

- [ ] Revisão desafio semana #10 - Parte 1
- [ ] Revisão desafio semana #10 - Parte 2
- [ ] Errata correção do desafio a semana #10 (próximo vídeo)
- [ ] Revisão desafio semana #10 - Parte 3
- [ ] Laços (Loops)
- [ ] Saltos
- [ ] Desafio semana #11

### Aula 12

- [ ] Revisão desafio semana #11 - Parte 1
- [ ] Revisão desafio semana #11 - Parte 2
- [ ] Criação de objetos
- [ ] Criação de objetos - Object.create
- [ ] Métodos de objeto
- [ ] Arrays - Métodos

### Aula 13

- [ ] Revisão desafio semana #12 - Parte 1
- [ ] Revisão desafio semana #12 - Parte 2
- [ ] Arrays - toString, concat, unshit e shift
- [ ] slice e splice
- [ ] forEach, every, some
- [ ] map, filter e desafio da semana #13

### Aula 14

- [ ] Revisão do desafio da semana #13 - Parte 1
- [ ] Revisão do desafio da semana #13 - Parte 2
- [ ] Revisão do desafio da semana #13 - Parte 3
- [ ] reduce() e reduceRight()
- [ ] IndexOf(), lastIndexOf() e isArray()
- [ ] Desafio da semana #1
